### PR TITLE
Added Discord provider + tests

### LINKED ISSUE #273: Provide Discord OAuth2 implementation
I may work on this at some point if I understand the lib well enough.

In any case, I appreciate all the work that is put into httpx-oauth :D

### PR DESCRIPTION
**Pull request by williamhatcher**
Fixes #273

I also tested this with a real implementation to make sure it works.

### CODE REVIEW

**Comment by frankie567** [comment]
Hello @williamhatcher 👋 

Thank you for this contribution, very interesting! Looks good!

May I ask you to add it to the docs, following the same model as the others, e.g:

https://github.com/frankie567/httpx-oauth/blob/b06a32050c8a1dbb409d9d4b956fe1120879df1d/docs/oauth2.md?plain=1#L165-L174

**Comment by frankie567** [comment]
Thanks!

Well, to be honest, unless you *really* want to add Shopify because you need it, it's not a super necessary addition, IMO.

**Comment by williamhatcher** [comment]
@frankie567 I added Discord to the docs like you asked, and noted that I contributed the Discord class. If you'd rather not have the contributor name in the docs, then I'm happy to remove it.

**Comment by frankie567** [comment]
Looks good! Thank you @williamhatcher 👍

**Pull request merged**
