### PR TITLE
clients: add Reddit OAuth2 client

### PR DESCRIPTION
**Pull request by Forst**
Some differences from the default OAuth2 behaviour:

* Client ID/secret are passed via HTTP Basic auth
* In case of failure, their API doesn't always return 400

To-do:
* [x] Add client documentation
* [x] Check test coverage

### CODE REVIEW

**Comment by Forst** [comment]
Have to add this client to the docs, and check the test coverage.

**Comment by Forst** [comment]
@frankie567 Hello! Any chance you could have a look at this, please? Much appreciated :)

**Comment by frankie567** [comment]
Hi @Forst! Sorry for this massive delay 😅

Thank you for your proposal! What troubles me is that we are not able to return the email address. Is there really no way to get it from Reddit?

**Comment by Forst** [comment]
> Is there really no way to get it from Reddit?

Doesn't look like it's possible: https://www.reddit.com/r/redditdev/comments/e6i85y/comment/f9qzk96/

I couldn't find it anywhere in the API docs either.

**Comment by frankie567** [comment]
Ok, thank you for the reference! That makes using Reddit as an identity provider quite hard, but they surely have their reasons. 

I see you added a clear note about it in the docs, so that should work. Maybe pass it as a `warning` instead of just a `note`?

Also (really sorry), but I just changed the way I manage dependencies so, would you mind rebase your branch so the CI can pass?

**Comment by Forst** [comment]
> Maybe pass it as a `warning` instead of just a `note`?

Done

> would you mind rebase your branch so the CI can pass?

Also done :)

**Pull request merged**
